---
driver:
  name: vagrant

platforms:
- name: ubuntu-20-04
  driver_config:
    box: bento/ubuntu-20.04

- name: ubuntu-22-04
  driver_config:
    box: bento/ubuntu-22.04
- name: ubuntu-24-04
  driver_config:
    box: bento/ubuntu-24.04
- name: ubuntu-26-04
  driver_config:
    box: bento/ubuntu-26.04

- name: centos-stream-9
- name: centos-stream-10

- name: almalinux-8
- name: almalinux-9
- name: almalinux-10

- name: rockylinux-8
- name: rockylinux-9
- name: rockylinux-10

- name: oracle-8
- name: oracle-9
- name: oracle-10

- name: debian-12
- name: debian-13

- name: fedora-43
- name: fedora-44

provisioner:
  name: chef_zero
  product_name: cinc
<% if ENV['CINC_VERSION'] %>
  product_version: '<%= ENV['CINC_VERSION'] %>'
<% end %>

verifier:
  name: inspec
  sudo: true

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
- name: modules_disabled
  run_list:
  - recipe[test]
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - path: test/integration/default
    attributes:
      kernel_modules_disabled: 1
